insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 4154872, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 2581882, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 1453574, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Goiás', 5360436, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Goiás', 5027304, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 4129176, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 2985238, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 5363265, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 3128956, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 8280011, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 5133381, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 3244598, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraíba', 4628417, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Goiás', 1182949, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 8332845, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 7716906, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 2376376, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 1081215, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 8643774, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 8643109, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 7724874, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Goiás', 5397132, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 6151009, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 5082002, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 6346453, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 5312049, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 4421137, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 6167616, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 4311376, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 1038666, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 5072515, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 7223391, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 8669380, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 6746185, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 4740099, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 9434710, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 8145926, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 4882310, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 3043429, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 9750051, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 2195822, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 5402538, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia ', 2611638, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 8526877, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 5326964, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia ', 3187618, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 9721735, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 9010215, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 9638091, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 8665385, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 6676945, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 8663759, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Sergipe', 2434054, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 2941879, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 1562541, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 6009672, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 6103253, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 8190707, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 2182160, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 2196810, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 9469014, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 8619086, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 2912282, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 5769417, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 8174997, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 9223803, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 1465610, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 2297859, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso do Sul', 5377857, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 5652561, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Maranhão', 9762118, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 8385757, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 5959680, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 6554839, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 9832668, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 6445880, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 5801504, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 5658513, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 3708542, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 3183319, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 8118044, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 5004981, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Ceará', 9513665, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 2415073, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 5334927, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 9344261, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Norte', 1836139, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 8674588, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Ceará', 8319228, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 9871121, 'Centro-Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 1058109, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Ceará', 6262192, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amapá', 4695262, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 1272683, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Espírito Santo', 6234407, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Espírito Santo', 3885187, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 4908115, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Espírito Santo', 4806109, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pará', 2965252, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Ceará', 8859222, 'Nordeste');
