insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 15, 275, '1 Estrela', 5650.03);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 98, 183, '5 Estrela', 3235.94);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 33, 185, '2 Estrela', 2872.51);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 54, 75, '1 Estrela', 8206.87);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 71, 78, '1 Estrela', 3876.82);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 83, 431, '5 Estrela', 2889.86);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 73, 432, '1 Estrela', 2669.75);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 18, 130, '2 Estrela', 7228.84);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 49, 360, '5 Estrela', 8664.35);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 2, 450, '3 Estrela', 4945.55);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 45, 127, '1 Estrela', 9109.23);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 16, 264, '4 Estrela', 3236.41);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 14, 240, '1 Estrela', 1820.1);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 41, 130, '4 Estrela', 5731.62);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 6, 340, '3 Estrela', 1024.02);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 97, 441, '5 Estrela', 768.06);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (41, 160, '2 Estrela', 6336.15);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 17, 398, '3 Estrela', 3855.64);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 100, 95, '3 Estrela', 3408.44);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 63, 58, '1 Estrela', 2263.25);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 4, 390, '1 Estrela', 4009.68);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 6, 243, '3 Estrela', 925.63);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 34, 68, '1 Estrela', 6007.73);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (83, 287, '2 Estrela', 3143.85);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 66, 199, '3 Estrela', 969.65);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 53, 415, '2 Estrela', 7305.25);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 5, 311, '3 Estrela', 4173.18);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 51, 422, '1 Estrela', 5833.65);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 66, 281, '3 Estrela', 8431.27);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 86, 35, '5 Estrela', 3036.29);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 85, 232, '3 Estrela', 4915.12);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 100, 243, '1 Estrela', 8236.19);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 88, 350, '1 Estrela', 6696.89);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 32, 395, '2 Estrela', 3900.98);
insert into Quarto(regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values ( 18, 313, '3 Estrela', 1324.19);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (682, 37, 54, '5 Estrela', 7821.46);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (781, 29, 500, '4 Estrela', 634.5);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (846, 61, 16, '2 Estrela', 8460.37);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (35, 79, 71, '5 Estrela', 9939.84);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (370, 23, 216, '4 Estrela', 8389.26);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (252, 51, 500, '4 Estrela', 7422.58);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (406, 65, 166, '3 Estrela', 3998.48);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (323, 15, 69, '2 Estrela', 4226.23);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (48, 52, 470, '4 Estrela', 2179.55);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (110, 93, 259, '3 Estrela', 8083.62);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (815, 20, 169, '2 Estrela', 9085.9);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (875, 94, 205, '1 Estrela', 3478.88);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (539, 49, 111, '2 Estrela', 8193.25);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (331, 26, 347, '4 Estrela', 7758.35);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (785, 9, 160, '4 Estrela', 8811.25);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (523, 35, 325, '5 Estrela', 1929.55);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (132, 27, 252, '2 Estrela', 4867.07);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (931, 75, 285, '4 Estrela', 5260.55);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (459, 84, 319, '2 Estrela', 6428.04);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (628, 36, 69, '5 Estrela', 6290.5);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (4, 85, 262, '2 Estrela', 9624.25);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (113, 33, 330, '5 Estrela', 1594.99);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (155, 5, 67, '5 Estrela', 9683.71);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (982, 56, 195, '2 Estrela', 5006.56);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (317, 97, 99, '5 Estrela', 1074.09);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (740, 45, 451, '1 Estrela', 7081.44);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (205, 20, 29, '2 Estrela', 9428.96);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (990, 61, 207, '2 Estrela', 6969.17);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (748, 91, 264, '2 Estrela', 7614.66);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (410, 59, 257, '3 Estrela', 3129.7);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (948, 72, 439, '1 Estrela', 9342.24);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (3, 65, 340, '2 Estrela', 1321.18);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (843, 2, 108, '2 Estrela', 7140.46);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (761, 16, 48, '5 Estrela', 896.59);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (694, 94, 355, '2 Estrela', 6585.79);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (169, 4, 380, '4 Estrela', 3237.63);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (592, 84, 423, '5 Estrela', 3170.18);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (879, 59, 21, '3 Estrela', 757.57);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (127, 63, 131, '3 Estrela', 4321.91);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (243, 35, 211, '5 Estrela', 4331.2);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (739, 50, 362, '5 Estrela', 6538.22);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (747, 57, 466, '5 Estrela', 9013.24);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (798, 42, 172, '4 Estrela', 3550.49);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (340, 78, 449, '1 Estrela', 985.64);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (970, 61, 213, '5 Estrela', 7793.93);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (414, 41, 43, '4 Estrela', 8979.46);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (94, 69, 426, '5 Estrela', 2359.8);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (904, 20, 121, '4 Estrela', 3020.88);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (879, 66, 457, '5 Estrela', 9919.01);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (690, 60, 108, '5 Estrela', 9149.05);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (818, 43, 471, '4 Estrela', 8555.94);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (331, 96, 78, '2 Estrela', 3697.67);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (168, 35, 64, '2 Estrela', 7555.36);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (51, 96, 332, '5 Estrela', 8477.18);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (757, 90, 478, '3 Estrela', 9171.53);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (957, 91, 384, '1 Estrela', 8295.05);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (392, 30, 18, '1 Estrela', 5744.43);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (615, 43, 25, '4 Estrela', 3549.77);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (875, 57, 37, '2 Estrela', 5543.65);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (953, 83, 140, '3 Estrela', 1060.85);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (373, 85, 176, '4 Estrela', 6766.23);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (784, 39, 295, '4 Estrela', 5389.94);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (801, 17, 319, '3 Estrela', 5889.77);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (112, 11, 214, '5 Estrela', 5511.0);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (804, 67, 462, '2 Estrela', 1384.56);
insert into Quarto  (contratoAluguel_idContratoAluguel, regiao_idRegiao, proprietario_idProprietario, avaliacao, preco) values (962, 59, 83, '3 Estrela', 5105.42);
