insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 4154872, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 2581882, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pará', 1453574, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 5360436, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraíba', 5027304, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraíba', 4129176, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 2985238, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 5363265, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 3128956, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 8280011, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Tocantins', 5133381, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Sergipe', 3244598, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraíba', 4628417, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 1182949, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Tocantins', 8332845, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 7716906, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 2376376, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 1081215, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso do Sul', 8643774, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 8643109, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Maranhão', 7724874, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 5397132, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amapá', 6151009, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 5082002, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraíba', 6346453, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Espírito Santo', 5312049, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 4421137, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 6167616, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 4311376, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 1038666, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amapá', 5072515, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 7223391, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 8669380, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Norte', 6746185, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Sergipe', 4740099, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 9434710, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Roraima', 8145926, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 4882310, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 3043429, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 9750051, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 2195822, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Amapá', 5402538, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Espírito Santo', 2611638, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 8526877, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 5326964, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso do Sul', 3187618, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 9721735, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Tocantins', 9010215, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pará', 9638091, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Maranhão', 8665385, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 6676945, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Roraima', 8663759, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Sergipe', 2434054, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio de Janeiro', 2941879, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Roraima', 1562541, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 6009672, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Norte', 6103253, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Ceará', 8190707, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 2182160, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pará', 2196810, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 9469014, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Pernambuco', 8619086, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 2912282, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 5769417, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 8174997, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Sergipe', 9223803, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 1465610, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('São Paulo', 2297859, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Alagoas', 5377857, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Tocantins', 5652561, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Maranhão', 9762118, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 8385757, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 5959680, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Paraná', 6554839, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 9832668, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 6445880, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 5801504, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Piauí', 5658513, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Sul', 3708542, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 3183319, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 8118044, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 5004981, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 9513665, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 2415073, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 5334927, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Bahia', 9344261, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Norte', 1836139, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 8674588, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 8319228, 'Noroeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Minas Gerais', 9871121, 'Leste');
insert into Regiao  (estado, cep, nomeregiao) values ('Distrito Federal', 1058109, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Goiás', 6262192, 'Nordeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Acre', 4695262, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 1272683, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Mato Grosso', 6234407, 'Sudeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rondônia', 3885187, 'Oeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Rio Grande do Norte', 4908115, 'Sul');
insert into Regiao  (estado, cep, nomeregiao) values ('Roraima', 4806109, 'Sudoeste');
insert into Regiao  (estado, cep, nomeregiao) values ('Santa Catarina', 2965252, 'Norte');
insert into Regiao  (estado, cep, nomeregiao) values ('Amazonas', 8859222, 'Noroeste');
